### ISSUE TITLE
mod_p0f.c:1302:7: error: void value not ignored as it ought to be

### ISSUE THREAD

**Issue by Mimikoo** [Castaglia/proftpd-mod_p0f#1]
gcc  -DHAVE_CONFIG_H  -DLINUX  -I. -I../.. -I../../include -I/usr/include/libxml2 -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing -c mod_p0f.c
mod_p0f.c: In function 'set_p0fpath':
mod_p0f.c:1302:7: warning: dereferencing 'void *' pointer
 1302 |   if (*cmd->argv[1] != '/') {
      |       ^~~~~~~~~~~~~
mod_p0f.c:1302:7: error: void value not ignored as it ought to be
mod_p0f.c: In function 'set_p0fsignatures':
mod_p0f.c:1355:7: warning: dereferencing 'void *' pointer
 1355 |   if (*cmd->argv[1] != '/') {
      |       ^~~~~~~~~~~~~
mod_p0f.c:1355:7: error: void value not ignored as it ought to be
mod_p0f.c: In function 'set_p0fsocket':
mod_p0f.c:1375:7: warning: dereferencing 'void *' pointer
 1375 |   if (*cmd->argv[1] != '/') {
      |       ^~~~~~~~~~~~~
mod_p0f.c:1375:7: error: void value not ignored as it ought to be
make[2]: *** [Makefile:23: mod_p0f.o] Error 1

**Comment by Castaglia** [comment]
This should now be fixed in `master`.  Care to try again?
